{
 "title": "Eneko_Manel_Ruben",
 "time": { "from": "2025-04-05T10:01:20.680Z", "to": "2025-04-05T10:06:20.680Z" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 11, "x": 6, "y": 0 },
   "options": {
    "content": "# Visualización de datos - Eneko, Manel y Rubén"
   }
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "targets": [
    { "rawSql": "SELECT * FROM turbina" }
   ]
  },
  {
   "title": "Media de potencia activa",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(lv_active_power_kw) AS \"Media de potencia activa\" FROM turbina"
    }
   ]
  },
  {
   "title": "Media de velocidad del viento",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(wind_speed_ms) FROM turbina LIMIT 50 "
    }
   ]
  },
  {
   "title": "Media de curva de potencia teórica",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(theoretical_power_curve_kwh) FROM turbina LIMIT 50 "
    }
   ]
  },
  {
   "title": "Media de dirección del viento (grados)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(wind_direction_deg) FROM turbina LIMIT 50 "
    }
   ]
  },
  {
   "title": "Max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(lv_active_power_kw) FROM turbina LIMIT 50 "
    }
   ]
  },
  {
   "title": "Min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MIN(lv_active_power_kw) FROM turbina LIMIT 50 "
    }
   ]
  },
  {
   "title": "Max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(wind_speed_ms) FROM turbina LIMIT 50 "
    }
   ]
  },
  {
   "title": "Min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MIN(wind_speed_ms) FROM turbina LIMIT 50 "
    }
   ]
  },
  {
   "title": "Max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(theoretical_power_curve_kwh) FROM turbina LIMIT 50 "
    }
   ]
  },
  {
   "title": "Min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MIN(theoretical_power_curve_kwh) FROM turbina LIMIT 50 "
    }
   ]
  },
  {
   "title": "Max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(wind_direction_deg) FROM turbina LIMIT 50 "
    }
   ]
  },
  {
   "title": "Min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MIN(wind_direction_deg) FROM turbina LIMIT 50 "
    }
   ]
  }
 ]
}